### ISSUE TITLE
Not compatible with jQuery.live

### ISSUE THREAD

**Issue by jamesarosen** [mathusiast/jquery.hotkeys#11]
See http://jsfiddle.net/6WJKu/

**Comment by jamesarosen** [comment]
I think the problem is the logic here:

```
// Don't fire in text-accepting inputs that we didn't directly bind to
if ( this !== event.target && (/textarea|select/i.test( event.target.nodeName ) ||
  event.target.type === "text") ) {
  return;
}
```

On a `jQuery.live` event, `this` is the document (or optionally the live context in jQuery 1.4), so this test fails. Perhaps there's a way to use `event.srcElement` instead of `this`?

**Comment by kingster** [comment]
well using event.srcElement makes it incompatible with ns/firefox

**Comment by jamesarosen** [comment]
@kingster can you elaborate? Does that property not exist in Firefox?

**Comment by kingster** [comment]
Firefox doesnt have a event.srcElement it does only have event.target 

Read more : http://www.google.com/?q=event.srcElement
