### ISSUE TITLE
Can any one fix the unbind bug?

### ISSUE THREAD

**Issue by linjuming** [mathusiast/jquery.hotkeys#12]
I download many versions, but the "ctrl+s" bug exists in every version, it can not use unbind method, can you great guys fix the bug? I need the methed for some of my actions.

**Comment by TrevorBurnham** [comment]
Just to elaborate on this, linjuming is referring to the test in `test-static-07.html`. The command

```
jQuery(document).unbind('keydown', '⌃+s');
```

has no apparent effect (whereas a straight `unbind('keydown')` works). It seems that the ability to unbind specific keys simply doesn't exist in jQuery Hotkeys.
