### ISSUE TITLE
keypress doesn't fire on special keys

### ISSUE THREAD

**Issue by YuppY** [mathusiast/jquery.hotkeys#7]
Plugin handles special keys only on keydown/keyup. This is invalid behavior because special key triggers all kinds of events with valid keyCode. Though alphanumeric keys valid charCode available only on keypress events. Here is patch:

```
                return;
            }

-           // Keypress represents characters, not special keys
-           var special = event.type !== "keypress" && jQuery.hotkeys.specialKeys[ event.which ],
-               character = String.fromCharCode( event.which ).toLowerCase(),
-               key, modif = "", possible = {};
+           var special = jQuery.hotkeys.specialKeys[ event.keyCode ],

+               // characters are represented only in keypress
+               character = event.type === "keypress" && String.fromCharCode( event.which ).toLowerCase(),
+               modif = "", possible = {};
+
            // check combinations (alt|ctrl|shift+anything)
            if ( event.altKey && special !== "alt" ) {
                modif += "alt+";
@@ -73,8 +74,9 @@

            if ( special ) {
                possible[ modif + special ] = true;
+           }

-           } else {
+           if ( character ) {
                possible[ modif + character ] = true;
                possible[ modif + jQuery.hotkeys.shiftNums[ character ] ] = true;
```

**Comment by jonibatista** [comment]
Yeah, this patch solves the problem but then we' aren't able to use the remaining special keys.

**Comment by YuppY** [comment]
Thank you for commiting. Note that you haven't included if(character) check.
Which special keys are not working?

**Comment by jonibatista** [comment]
Please ignore my commit. It solves the return key but adds more problems. Sorry for that.

Ok, as I understood any key identified by a string doesn't fire only in the keypress event. For example, if I bind a handler to keypress.a it works perfectly (a.length = 1 => char) but, if instead a I bind to keypress.return the event doesn't fire (return.length > 1 => string).

**Comment by YuppY** [comment]
I've made pull request for jresig fork that fixes this issue https://github.com/jeresig/jquery.hotkeys/pull/28
